######################
## Lecture 2 R Code ##
######################

#Slide 2
true.mu <- 64.5
true.sigma <- 2.5
n <- 10
#Setting the seed allows one to generate the same numbers each time.
set.seed(22)  
sample10 <- rnorm(n, mean=true.mu, sd=true.sigma)
paste("heights:", paste(round(sample10, 1), collapse=" "), sep=" ")
par(cex=0.5)
hist(sample10, freq=FALSE, xlab="Height in Inches", main="Sample of 10 Women")

#Slides 3, 4 and 5
#Repeat code above but change the value of the sample size n to
#the necessary value (n=50, 500 and 1000) as well as the 
#reference to n=10 in variable names and plot titles.
par(mfrow = c(2,2), cex = 0.5) #Create 2x2 grid for plots
set.seed(22)  
sample50 <- rnorm(50, mean=true.mu, sd=true.sigma)
sample500 = rnorm(500, mean=true.mu, sd=true.sigma)
sample1000 = rnorm(1000, mean=true.mu, sd=true.sigma)
hist(sample10, freq=FALSE, xlab="Height in Inches", main="n=10")
abline(v = true.mu, col = "red", lwd = 2)
hist(sample50, freq=FALSE, xlab="Height in Inches", main="n=50")
abline(v = true.mu, col = "red", lwd = 2)
hist(sample500, freq=FALSE, xlab="Height in Inches", main="n=500")
abline(v = true.mu, col = "red", lwd = 2)
hist(sample1000, freq=FALSE, xlab="Height in Inches", main="n=1000")
abline(v = true.mu, col = "red", lwd = 2)
par(mfrow = c(1,1))

#Slide 12
par(mfrow=c(1, 2), cex=0.5) #Creates one row of 2 plots
set.seed(22)
true.mu <- 64.5
true.sigma <- 2.5
sample1000 <- c(rnorm(1000, mean=true.mu, sd=true.sigma))
height.range <- range(sample1000)
XX <- seq(from=height.range[1], to=height.range[2], length=1000)
plot(XX, dnorm(XX, mean=true.mu, sd=true.sigma), type="l", main="N(64.5, 2.5)", xlab="Height in Inches", ylab="Density", lwd=2)

hist(sample50, freq=FALSE, xlab="Height in Inches", main=paste("Mean=", round(mean(sample50), 2), ", SD=", round(sd(sample50), 2), sep=""))
lines(density(x=sample50), col="red", lwd=2)

par(mfrow=c(1,1)) #Reset to single plot


#Normal Distributions Calclulations

## P(X<66)
pnorm(q=66, mean=64.5, sd=2.5) 
## P(X<60)
pnorm(q=60, mean=64.5, sd=2.5) 
## The answer
pnorm(q=66, mean=64.5, sd=2.5) - pnorm(q=60, mean=64.5, sd=2.5) 

#OR can do the following using the default values of mean=0 and sd=1:

## P(X<66) = P(Z < 0.6)
pnorm(q=0.6) 
## P(X<60) = P(Z < -1.8)
pnorm(q=60, mean=64.5, sd=2.5) 
## The answer
pnorm(q=66, mean=64.5, sd=2.5) - pnorm(q=60, mean=64.5, sd=2.5) 


#Normal Quantile Plots
#par(cex=0.5)
true.mu <- 64.5
true.sigma <- 2.5
set.seed(22)  #Useful if you want to repeat the same values generated by rnorm()
sample50 <- rnorm(50, mean=true.mu, sd=true.sigma)
qqnorm(sample50, xlab = "Z-Scores")
qqline(sample50)



